server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order_food
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update

telegram:
    admin: -1001532538433
    chanel: -100776853235
    chanel-link: 'https://t.me/shodiyors_channel'
    bot-username: 'KayoSupportBot'
    bot-token: '5494048456:AAHm7-APSn5zASCqIc8hxxQHQonTG9sinZk'
