package com.example.order_food.enums
enum class LocalizationTextKey {
    //----------BUTTON TEXT (START)-----------
    ENTER_CONTACT_BUTTON,
    ORDER_BUTTON,
    ABOUT_US_BUTTON,
    SETTINGS_BUTTON,
    ADD_LOCATION_BUTTON,
    PANNIER_BUTTON,
    BACK_BUTTON,
    CONFIRMATION_BUTTON,
    LOCATION_BUTTON,
    CHOOSE_LANGUAGE_BUTTON,
    PLACING_ORDER_BUTTON,


    //----------BUTTON TEXT (END)-----------


    // ----------MESSAGE TEXT (START)-----------
    CHOOSE_LANGUAGE_MESSAGE,
    INPUT_CONTACT_MESSAGE,
    INPUT_MENU_MESSAGE,
    ORDER_BUTTON_MESSAGE,
    LOCATION_BUTTON_MESSAGE,
    WRONG_COMMAND_MESSAGE,
    CHOOSE_QUANTITY_MESSAGE,
    CONTINUE_ORDER_MESSAGE,
    ABOUT_US_MESSAGE,
    SETTINGS_MESSAGE,
    CHOOSE_LANGUAGE_BUTTON_MESSAGE,
    CONFIRMATION_BUTTON_MESSAGE


    // ----------MESSAGE TEXT (END)-----------

}